image: node:latest

stages:
  - Install
  - Build
  - Test

cache:
  paths: 
    - node_modules/

install project:
  stage: Install
  script: 
    - npm install

build project:
  stage: Build
  script: 
    - npm build

jest tests:
  stage: Test
  script:
    - npm test
